// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iLit.Infrastructure;

namespace iLit.Infrastructure.Migrations
{
    [DbContext(typeof(iLitContext))]
    partial class iLitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("iLit.Infrastructure.Edge", b =>
                {
                    b.Property<int>("edgeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fromNodeID")
                        .HasColumnType("int");

                    b.Property<int>("toNodeID")
                        .HasColumnType("int");

                    b.HasKey("edgeID");

                    b.HasIndex("fromNodeID", "toNodeID")
                        .IsUnique();

                    b.ToTable("Edges");

                    b.HasCheckConstraint("CK_Edge_From_To_ID", "[fromNodeID] != [toNodeID]");
                });

            modelBuilder.Entity("iLit.Infrastructure.Node", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("title")
                        .IsUnique();

                    b.ToTable("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
